# Generated by Django 5.2.7 on 2025-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list')),
                ('education', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('social_links', models.TextField(blank=True, help_text='Comma-separated: label|url')),
            ],
        ),
    ]
